require('options')
require('plugins')
require('colorscheme')
require('lsp')
require('setup_mason')
require('setup_cmp')
require('keymaps')
require('setup_telescope')
require('treesitter')
require('neotree')
-- require('setup_airline')
require('setup_codecompanion')
require('setup_null')
